// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "description": "獲取系統中的所有用戶列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "獲取所有用戶",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_models.UsersCollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "創建一個新的用戶",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "創建新用戶",
                "parameters": [
                    {
                        "description": "用戶信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/user_models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "通過ID獲取特定用戶的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "獲取特定用戶",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用戶ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新特定用戶的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "更新用戶",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用戶ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用戶信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "刪除特定用戶",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "刪除用戶",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用戶ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user_models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "user_models.APIResponse": {
            "description": "API 通用響應結構",
            "type": "object",
            "properties": {
                "_links": {
                    "description": "HATEOAS 連結 (可選)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user_models.HATEOASLink"
                    }
                },
                "data": {
                    "description": "響應資料 (可選)"
                },
                "error": {
                    "description": "錯誤訊息 (可選)",
                    "type": "string",
                    "example": "錯誤訊息"
                },
                "message": {
                    "description": "響應訊息",
                    "type": "string",
                    "example": "操作成功"
                },
                "status": {
                    "description": "HTTP 狀態碼",
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "user_models.HATEOASLink": {
            "description": "HATEOAS 連結結構",
            "type": "object",
            "properties": {
                "href": {
                    "description": "連結目標 URL",
                    "type": "string",
                    "example": "http://api.example.com/users/1"
                },
                "method": {
                    "description": "HTTP 方法",
                    "type": "string",
                    "example": "GET"
                },
                "rel": {
                    "description": "關係類型",
                    "type": "string",
                    "example": "self"
                },
                "title": {
                    "description": "連結描述",
                    "type": "string",
                    "example": "取得使用者資訊"
                }
            }
        },
        "user_models.User": {
            "description": "用戶模型",
            "type": "object",
            "required": [
                "address",
                "age",
                "email",
                "name",
                "phone",
                "sex"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "台北市"
                },
                "age": {
                    "type": "integer",
                    "example": 20
                },
                "created_at": {
                    "type": "string",
                    "example": "2021-01-01T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "zhangsan@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "name": {
                    "type": "string",
                    "example": "張三"
                },
                "phone": {
                    "type": "string",
                    "example": "1234567890"
                },
                "sex": {
                    "type": "string",
                    "example": "男"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-01-01T00:00:00Z"
                }
            }
        },
        "user_models.UserResponse": {
            "description": "符合 HATEOAS 的使用者響應結構",
            "type": "object",
            "properties": {
                "_links": {
                    "description": "HATEOAS 連結",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user_models.HATEOASLink"
                    }
                },
                "data": {
                    "description": "使用者資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user_models.User"
                        }
                    ]
                }
            }
        },
        "user_models.UsersCollectionResponse": {
            "description": "符合 HATEOAS 的多使用者響應結構",
            "type": "object",
            "properties": {
                "_links": {
                    "description": "HATEOAS 連結",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user_models.HATEOASLink"
                    }
                },
                "data": {
                    "description": "使用者資料陣列",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user_models.User"
                    }
                },
                "page": {
                    "description": "頁碼",
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "description": "每頁大小",
                    "type": "integer",
                    "example": 10
                },
                "total": {
                    "description": "總資料數",
                    "type": "integer",
                    "example": 100
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Go API with Gin and MongoDB",
	Description:      "這是一個使用 Gin 和 MongoDB 的 RESTful API 服務",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
